# Generated by Django 5.0.3 on 2024-03-30 15:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('cleaned_text', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Очищенный список слов')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='ProcessedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('tf', models.FloatField(blank=True, null=True, verbose_name='Частота слова')),
                ('idf', models.FloatField(blank=True, null=True, verbose_name='Обратная частота документа')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.uploadedfile', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Processed Word',
                'verbose_name_plural': 'Processed Words',
                'db_table': 'word',
            },
        ),
    ]
